#name: "Docker Actions"

#on: [push]

#jobs:
#  action:
#    runs-on: "ubuntu-latest"
#    steps:
#      - uses: actions/checkout@v1

#      - name: "hello-action"
#        uses: ./.github/actions/hello-world
#        with:
#          firstGreeting: "Mr. White"
#          secondGreeting: "Mr. Orange"
#          thirdGreeting: "Mr. Pink"


name: Docker Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: meow
        uses: ./.github/actions/cat-facts
